### ISSUE TITLE
Creation of new atlases.

### ISSUE THREAD

**Issue by AllisonMcDonald** [brainglobe/bg-atlasapi#103]
Hello there,

I have been really interested to see cellfinder and brainglobe grow in the last few years, great job on this open-source package! But I'm working with rat brains, and currently, there are no compatible rat atlases available. Are there plans to create a compatible rat atlas? And if not, what would it take to create a rat atlas in the correct format to work with other brainglobe packages? I'm interested in contributing if my skill set allows for it. 

Best regards,
Allison McDonald
PhD student
Behavioural & Translational Neuroscience Lab, VUmc, Amsterdam, NL.

**Comment by adamltyson** [comment]
Hi Alison,

We really need to write this up properly, but what you'll need is:
* A 3D structural reference image, e.g. just autofluorescence, MRI etc. Ideally similar to the modality you want to register
* A 3D annotations image (same size and shape as the structural image), where each brain area is defined by a unique voxel value
* Some information (e.g. csv file) of what brain area corresponds to each unique voxel value, and any brain region hierarchy information
* Ideally the 3D meshes of each brain area, but we can generate these

Then we have template scripts that can be used to package up the atlas.

Hope this helps, get in touch if we can help at all.

Adam

**Comment by adamltyson** [comment]
I've renamed this to track the general issue of improving the process and documentation for adding new atlases.

**Comment by MathieuBo** [comment]
Hi! 

Following our previous [discussion ](https://github.com/brainglobe/brainrender/issues/150), I think I am ready to contribute the rhesus monkey atlas. 
Could you contact me at: mathieu.bourdenx <at> u-bordeaux.fr to see what are the next steps? 

Thanks!
Mathieu

**Comment by oilbird** [comment]
Hi, 

I wanted to know if I can build an atlas (zebra finch, other birds) from  a series of 2d Nissl slices? if yes, how would I label each region? sorry if this is very basic. Thank you and thank you in advance.


Cristian

**Comment by adamltyson** [comment]
Hi @oilbird, we currently only support 3D atlases at the moment, so for this to work you would need to ensure that each of your 2D sections were registered to each other, to create an aligned volume.

How you label each region is up to you, but to create the image, you could use something like ImageJ/FIJI or napari.

**Comment by LSilvagnoli** [comment]
Hi @adamltyson ,

I wanted to know if there is a project on the allen atlas in the young mouse on this api. (such as P14).
is there any documentation listing ongoing works ?

thx in advance.

**Comment by adamltyson** [comment]
Hi @LSilvagnoli,

Ongoing work to develop new atlases is over at https://github.com/brainglobe/bg-atlasgen. We don't yet have a P14 mouse atlas, but I think https://github.com/brainglobe/bg-atlasgen/pull/11 could be adapted to include other atlases from @yoda-vid's [paper](https://elifesciences.org/articles/61408) which I think includes P4 and P28 atlases. Is this right @r4deepr?

**Comment by yoda-vid** [comment]
Thanks, @adamltyson and @LSilvagnoli. Yes, those atlases including the [P14 mouse](https://search.kg.ebrains.eu/?facet_type[0]=Dataset&q=developing%20mouse#114e50aa-156c-4283-af73-11b7f03d287e) are currently available on EBRAINS. Would be awesome if @pr4deepr's PR could be adapted to include them on this API as well (thanks for all your work on this!).

**Comment by LSilvagnoli** [comment]
Thanks @adamltyson and @yoda-vid for your answers on this subject.

Please let me know if there is any advancement about including those atlases on this API.

**Comment by adamltyson** [comment]
Closing this now there are some docs on the website (https://docs.brainglobe.info/bg-atlasapi/adding-a-new-atlas).

If anyone is still interested in contributing a new atlas, I have some more bandwidth to help out, so get in touch.
