### ISSUE TITLE
List of available atlases

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#107]
We have the `brainglobe list` command to list all available atlases, and some are on the [online docs](https://docs.brainglobe.info/bg-atlasapi/introduction), but perhaps it would be best to expand upon this list (and keep it updated) with a small description of each atlas and how they relate to each other?

**Comment by adamltyson** [comment]
Yep, maybe once the new atlases are in (and the meshes are improved), we should write a bit about them and advertise?

**Comment by FedeClaudi** [comment]
Yeah!

We could also add a `--describe` flag to `brainglobe list` to print out the [https://github.com/brainglobe/bg-atlasapi/blob/master/bg_atlasapi/descriptors.py](metadata of) all of atlases too?

**Comment by adamltyson** [comment]
Maybe only for a specific atlas, otherwise this could get huge?

Although, it would be great to be able to print this without downloading the whole atlas first.

We should think more about discoverability of atlases though, as the numbers increase, they'll get harder to find.

**Comment by FedeClaudi** [comment]
agreed. it should be possible to get some basic info/metadata without having to download stuff. I think we for sure should give the different atlas more space on the online documentaiton

**Comment by adamltyson** [comment]
More generally, I think we should spend a bit time (that we don't have) on making the docs a bit more coherent and advertising the whole ecosystem a bit better.

**Comment by FedeClaudi** [comment]
That we don't have being the key part!

**Comment by adamltyson** [comment]
Docs added here - https://brainglobe.info/documentation/bg-atlasapi/usage/atlas-details.html
