### ISSUE TITLE
545.obj missing in allen_mouse_25um ?

### ISSUE THREAD

**Issue by NicoKiaru** [brainglobe/bg-atlasapi#109]
Hi everybody, 

I don't really know where to check this, but I found a bug while trying to serialize the allen_mouse_25um_v1.2 atlas : 

`
C:\Users\nico\.brainglobe\allen_mouse_25um_v1.2\meshes\545.obj not found.
`

It seems this file is missing. Maybe that's only me ( a glitch during during the download), but maybe not ? Can you check whether this file is missing for you as well ? And if yes, can this be fixed ?

Thanks!

**Comment by NicoKiaru** [comment]
Hum, it seems this obj file is not even in https://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/annotation/ccf_2017/structure_meshes/

**Comment by NicoKiaru** [comment]
Maybe the issue is just that I don't know how to catch exceptions:

```
ReadError                                 Traceback (most recent call last)
~\.conda\envs\abba-bg\lib\site-packages\bg_atlasapi\structure_class.py in __getitem__(self, item)
     22             try:
---> 23                 self.data[item] = mio.read(self.data["mesh_filename"])
     24             except (TypeError, mio.ReadError):

~\.conda\envs\abba-bg\lib\site-packages\meshio\_helpers.py in read(filename, file_format)
     58         if not path.exists():
---> 59             raise ReadError(f"File {filename} not found.")
     60 

ReadError: File C:\Users\nico\.brainglobe\allen_mouse_25um_v1.2\meshes\545.obj not found.
```

**Comment by vigji** [comment]
I think that the problem is what you've found, we use the meshes from the allen institute and for some reason (maybe @FedeClaudi knows more) some regions don't have one ' maybe the're too small?
What are you trying to do? Maybe you can
```
try:
    whatever(mesh)
except ReadError:
    pass
```

**Comment by FedeClaudi** [comment]
I don't know why some meshes are missing! Maybe that they kept a region number from previous versions of the atlas but don't have a mesh for it any more.

Yeah the best thing you can do is to catch that error, sorry.

**Comment by NicoKiaru** [comment]
Here's my issue, I need to convert a dictionary from {string: object} to {string:string}.

For that I write the following:
```
    def data(self):
        dict_ori = self.atlas.structures[self.id]
        string_dict = {key: JString(str(value)) for key, value in dict_ori.items()} #keys_values}
        return string_dict
```

The error is raised when I write ` dict_ori.items()`. I don't know how to catch the error for one item only but let the iteration resumes for other items.

Maybe there's another way to make this conversion ?

**Comment by NicoKiaru** [comment]
Ok, I probably need to just loop through keys instead of items
