### ISSUE TITLE
Configurable config & atlas location

### ISSUE THREAD

**Issue by chrisroat** [brainglobe/bg-atlasapi#110]
It seems like $HOME/.brainglobe is hardcoded as the default location for atlas downloads.  I would like to be able to change this, but it seems that <python_location>/site-packages/bg_atlasapi/bg_config.conf is the hardcoded location for configuration that could change the download location.

I would suggest that site-packages not be written to, and that the default location of bg_config.conf be in the home directory (in .config/ or as .bg_config.conf).  If it is not present, then the current defaults could be used.

**Comment by adamltyson** [comment]
Yep, I think this sounds like a good idea. The current behaviour isn't great, I think it was inherited from another package.

We'd welcome a PR if you have the time @chrisroat!

**Comment by chrisroat** [comment]
I can do that.  Is it OK to drop support for the current behavior, given its still in alpha?

**Comment by adamltyson** [comment]
Yep, I think so, but we may think about how/when we release on PyPI - @vigji, @FedeClaudi?

**Comment by vigji** [comment]
I don't know about you guys, but I never had the need myself or head about issues from people with the need to change that, so I feel that dropping support for current behavior would not cause any trouble!

**Comment by adamltyson** [comment]
I've edited the file for multi-user installations, but I think anyone else who has done the same would be fine with a change.

**Comment by FedeClaudi** [comment]
Yeah this all sounds great!

**Comment by adamltyson** [comment]
Closing as complete. Still needs to be documented - https://github.com/brainglobe/brainglobe.github.io/issues/76
