### ISSUE TITLE
Consider removing the human atlas

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#113]
The human atlas is not perfect, when I created it I didn't finish everything correctly so the meshes have some problems (e.g. origin/scale.. ).  Since I didn't see much interest in it at the time I didn't develop it further and as such it's the only BG atlas in version `< 1`.  
![image](https://user-images.githubusercontent.com/17436313/156754392-482cfc0e-ae9b-483c-bcc3-b967e4d33b9d.png)

Given all of this, I would consider removing it from the list of available atlases until an improved version is made, as this can cause problems for people interested: https://github.com/brainglobe/brainrender/issues/196

Internally in BG there was some initial effort to improve the atlas by Rami Hamati, but I'm not sure if it has progressed very far. 

cc: @adamltyson  @vigji

**Comment by adamltyson** [comment]
We could remove it, or somehow mark that it's a WIP? Either make explicit what the version number means, or change the name?

**Comment by adamltyson** [comment]
I've seen people use this atlas (mostly for figures etc), so we should keep it in. Keeping the issue open to track improvements to it.
