### ISSUE TITLE
Mask from atlas failing at some leaves

### ISSUE THREAD

**Issue by HernandoMV** [brainglobe/bg-atlasapi#116]
When getting masks from atlas regions. I am using:
```
from bg_atlasapi import BrainGlobeAtlas
import imio

bg_atlas = BrainGlobeAtlas("allen_mouse_25um")
stack = bg_atlas.get_structure_mask(672) # for CP (see image below)
stack = stack.astype(bool)
imio.to_tiff(stack, "/path/to/image.tiff")
```
This gives an empty image
However, if you use the hierarchy above (485), it does work

![image](https://user-images.githubusercontent.com/6049065/161075077-dcf0fd57-9d70-4064-9f62-14188f09f183.png)

**Comment by vigji** [comment]
Ok, v1.0.2 is out, so just updating to the latest version should fix the issue!
