### ISSUE TITLE
`get_structure_mask` is very slow for structures with many children

### ISSUE THREAD

**Issue by sdiebolt** [brainglobe/bg-atlasapi#119]
With the Allen mouse brain atlas 25µm, a call to `atlas.get_structure_mask(997)` takes approximately 45 seconds on my computer to get the whole brain mask.

Looking at `get_structure_mask`'s definition, its documentation warns that the function isn't optimized. Optimizing it could be very easy: instead of gettting each descendant's mask one by one in a loop, we could simply get the list of descendant IDs and use `numpy.isin` to get the resulting mask.

Replacing `get_structure_mask` by 

```python
structure_id = atlas.structures[structure]["id"]
descendant_ids = [
    atlas.structures[descendant]["id"] 
    for descendant in atlas.get_structure_descendants(structure_id)
]
descendant_ids.append(structure_id)

mask_stack[np.isin(atlas.annotation, descendant_ids)] = structure_id
```

leads to a big improvement:  `atlas.get_structure_mask(997)` now runs in 4 seconds.

I'd be happy to submit a pull request if you're interested!

**Comment by vigji** [comment]
Sounds very reasonable! If you can that would be very welcome :) thanks for improving this!
