### ISSUE TITLE
[Question] Where is the default location for atlases on linux systems?

### ISSUE THREAD

**Issue by rcpeene** [brainglobe/bg-atlasapi#130]
I'm running into problems downloading a brain atlas on a remote binder instance that I don't have complete access to. I am hoping to manually move the atlas i'm interested in to the right location so that I will not have to download it within a jupyter notebook. Where should this be?

**Comment by adamltyson** [comment]
By default atlases are saved into `~/.brainglobe`, e.g. `/home/adam/.brainglobe/allen_mouse_10um_v1.2`
