### ISSUE TITLE
[BUG] Missing hemisphere in Allen human brain atlas

### ISSUE THREAD

**Issue by dbirman** [brainglobe/bg-atlasapi#174]
The allen human atlas only has one hemisphere, but there's no reason not to enforce consistency and just copy the annotations to the other hemisphere (and copy the 3D meshes as well)

**Comment by adamltyson** [comment]
Hi @dbirman, I'd rather not edit the atlas. It was created as a single hemisphere, and while I'm not sure if the differences would be apparent at the level of detail of this atlas, the brain isn't structurally symmetric. 

Do you need the Allen human atlas in particular? I think we should address this by adding one or more of the other excellent MRI atlases. 

I've raised https://github.com/brainglobe/bg-atlasgen/issues/85

**Comment by dbirman** [comment]
No preference for the allen human atlas. Just basing it off citations it seems like this one is very popular: https://www.nature.com/articles/nature18933?
