### ISSUE TITLE
[BUG] Progress bar is not displayed correctly when downloading an atlas using the CLI

### ISSUE THREAD

**Issue by IgorTatarnikov** [brainglobe/bg-atlasapi#177]
**Describe the bug**
The total size, percentage, and progress bar do not display correct values during download of a new atlas.

**To Reproduce**
Download an atlas using the CLI.

**Expected behaviour**
The progress bar should fill up, the percent should change, and the total download size should display during download.

**Screenshots**

![BGAtlasAPI_Bug](https://github.com/brainglobe/bg-atlasapi/assets/61896994/da74785b-c958-4af3-ad87-1d4e5f5a199c)

**Computer used (please complete the following information):**

- OS: Windows 10 Pro
- Version 10.0.19045 Build 19045
- Hardware specs i9-13900K, 32 GB RAM, RTX 4080

**Additional context**
Based on:

https://github.com/brainglobe/bg-atlasapi/blob/f5d689c98f86d42a7f67bb817ac9f960f4ec8bc1/bg_atlasapi/utils.py#L164C1-L176C1

It looks like the `retrieve_over_http` function expects a "content-length" field in the header which is no longer returned by the server. This sets `tot` to 0 causing the downstream consequences to the progress bar/percentage/total size displayed by Rich.

![BGAtlas_Postman](https://github.com/brainglobe/bg-atlasapi/assets/61896994/af7335af-9719-4ebf-98a3-80c0482738b3)

**Comment by adamltyson** [comment]
Related - https://github.com/brainglobe/bg-atlasapi/issues/121
