### ISSUE TITLE
Extract cellfinder csv -> json conversion

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#32]
There's a tool to generate the brain region json, but the functionality to convert the csv format to json should be extracted in case users want to define their atlas using the csv.

This could be an optional part of a generalised atlas generation function that could be edited by 3rd party users.

**Comment by FedeClaudi** [comment]
@vigji  have you done anything on this? Maybe we can add it as a method to the `Atlas` class?

**Comment by vigji** [comment]
Well, it concerns facilitating the atlas generation, and there's no real use case once the structure tree is generated (the tree to csv conversion is already there). I would leave this open but we don't need it for the release.

**Comment by FedeClaudi** [comment]
> (the tree to csv conversion is already there

That's what I was asking about, I forgot it already existed :)

**Comment by vigji** [comment]
Is this working now? The Kim source seems to describe hierarchy in a css right?

**Comment by adamltyson** [comment]
I think it works, but it was never extracted into its own tool

**Comment by vigji** [comment]
ok, but exists in the bg-atlasgen package, so I guess this can be closed?

**Comment by adamltyson** [comment]
Yep, I think so

**Comment by adamltyson** [comment]
Yeah maybe something like https://docs.brainglobe.info/brainreg/user-guide/notes
