### ISSUE TITLE
Remove atlas_gen from the distributed package

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#33]
Currently, both `brainatlas_api` and `atlas_gen` will be distributed based on `setup.py`. 

Shall we remove `atlas_gen`, and assume that users who install from pypi will only be using `brainatlas_api`, and anyone who wants to use `atlas_gen` will install from github?

**Comment by FedeClaudi** [comment]
yeah I think that's good. 
I expect >90% of the users won't be generating their own atlas, and those that will can get the code from github

**Comment by vigji** [comment]
Agreed, my refactoring was for moving in that direction. 

Also, long term when things consolidate we could move the package back outside.
