### ISSUE TITLE
Final repo name before release

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-atlasapi#43]
Are we sure about brainatlas-api? Before making it permanent, I would reconsider bgatlas-api for consistency, to have bg somewhere :)

**Comment by FedeClaudi** [comment]
I don't mind either way

**Comment by adamltyson** [comment]
I also don't mind either way. Realistically, not all of the repos in this org will end up having a nicely formatted name. However, considering this is one of the "core" tools, and only developers will see the name, I think I lean slightly towards `bgatlas-api`. 

To be picky, if we have hyphens in the names, would `bg-atlasapi` (and `bg-viewer`) potentially be better? It would help developers see that they are all related.

**Comment by vigji** [comment]
> I also don't mind either way. Realistically, not all of the repos in this org will end up having a nicely formatted name. However, considering this is one of the "core" tools, and only developers will see the name, I think I lean slightly towards `bgatlas-api`.

Agree that everything is not realistic and we can try to keep it at least for the core package newly built.

> To be picky, if we have hyphens in the names, would `bg-atlasapi` (and `bg-viewer`) potentially be better? It would help developers see that they are all related.

If we can change the viewer as well I am fine with this - I like picky :)

**Comment by FedeClaudi** [comment]
sure we can change it, not problemo.

**Comment by adamltyson** [comment]
I think it could be useful. e.g. When contributing to cellfinder, it's not clear that many of the dependencies are part of the same project, so people have developed weird workarounds, rather than fixing the dependency. Having `bg-atlasapi`, `bg-viewer` etc would be much more obvious.
