### ISSUE TITLE
Formatting of atlases table

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-atlasapi#46]
Trying to use the list atlases on my laptop, the table generated by list_atlases() in a notebook is impossible to read because everything is too squeezed (always from notebooks, and in terminal unless I widen it a lot from default).

<img width="817" alt="Screenshot 2020-06-30 at 10 07 41" src="https://user-images.githubusercontent.com/10400212/86100750-8ae1ee80-bab9-11ea-85ea-650a3a35cb8c.png">

Maybe we can drop the remote URL?

**Comment by FedeClaudi** [comment]
That's weird, I need to check rich docs, maybe there's a way to ensure a minimal column width. But yes in general the online path is not very useful.  Also not sure why it ends with `object ...`?

**Comment by FedeClaudi** [comment]
addressed in: https://github.com/brainglobe/brainatlas-api/pull/49

were you testing in a jupyter notebook? On which OS? 
In theory the column width should match the content...

**Comment by vigji** [comment]
Testing in a notebook on macOS 15''

**Comment by FedeClaudi** [comment]
looks like this for me.. 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/17436313/86174406-7cc3ba80-bb19-11ea-8bfe-57b7dfda095b.png">

**Comment by vigji** [comment]
Same for me now.
<img width="864" alt="Screenshot 2020-06-30 at 23 15 50" src="https://user-images.githubusercontent.com/10400212/86177888-aa176500-bb27-11ea-9586-0a7815fbafb1.png">

 Still, I would find it uninformative if there's no full name, so I would definitively try to ensure some column width

**Comment by FedeClaudi** [comment]
should be fixed with the latest commit in the PR
<img width="748" alt="image" src="https://user-images.githubusercontent.com/17436313/86178857-10e55000-bb21-11ea-9e8a-56316c422f04.png">

I had to add a hard-coded minimal width for the column, so we better not have atlases with more than 32 characters in the name :)

**Comment by vigji** [comment]
that would be annoying to type anyway :p 

I was also thinking that the local path is also quite redundant, once you print the brainglobe location in the header. What about keeping the table only for the first four entries, and place outside the table the local path and the remote url?

**Comment by FedeClaudi** [comment]
I thought to leave it in case atlases are saved in different folders. But maybe it's unnecessary as users can get the atlas path in other ways... maybe I'll leave it as optional?

**Comment by FedeClaudi** [comment]
As per https://github.com/brainglobe/brainatlas-api/pull/49 , now the local path is optional and disabled by default.

**Comment by FedeClaudi** [comment]
@vigji  are you happy with how it looks now?

**Comment by vigji** [comment]
Yep, beautiful!
