### ISSUE TITLE
Command line commands

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#48]
I think we should re-name the command line commands. `brainatlas` is not consistent with any of the rest. Suggestions?

https://github.com/brainglobe/brainatlas-api/blob/b8c277814cd5f8a9d18b66c799d7c8b146a45442/setup.py#L33

**Comment by vigji** [comment]
Agreed! Maybe I would go for bg-config, bg-list, and bg-update if we are renaming the repo bg-atlasapi?

**Comment by FedeClaudi** [comment]
sounds good, let's make sure to remember when we rename the repo

**Comment by FedeClaudi** [comment]
I've unified the commands here: https://github.com/brainglobe/bg-atlasapi/pull/53
so this is issue is obsolete, closing.
