### ISSUE TITLE
Distributing custom atlases

### ISSUE THREAD

**Issue by vigji** [brainglobe/bg-atlasapi#52]
I have the first occurrence in the lab of a scenario where I would need to generate an high res atlas of a subregion of fish brain. We mentioned this briefly with @adamltyson .

As I said there, by now I would keep it as a completely separate atlas package. Maybe for such scenarios, we can just add special metadata fields like "main reference atlas" - or something similar and "origin", and then handle transformations with bg space.

My main doubt atm is how to allow users to distribute custom atlases like this one, outside the general ones. I canmake a lab GIN with the package, and write custom functions for our custom download to brainglobe dir - once there, everything can be handled. Alternatively, we can have a command line argument to install custom new atlases from a link, maybe with a special prefix-suffix to make sure they stay out from the updating functions for core atlases?

 I just wanted to know whether you guys have some thoughts about this.

**Comment by FedeClaudi** [comment]
I think:

1. We should have guidelines for hosting atlases for people that want to share theirs. Put on GIN, minimal docs etc...
2. We could allow installing atlases from any URL pointing to some compressed data. Of course it would have to match the API format and all. Currently this can be done bu subclassing BGAtlas and specifying a new url. maybe we can have this as an argument + have a CLI for it?

**Comment by adamltyson** [comment]
This sounds good. Do we want to encourage people to submit PRs with atlas generation scripts? That way we can make changes to the atlas structure in future.

**Comment by vigji** [comment]
I think we should distinguish 2 scenarios:
1) People who want to contribute new atlases (eg new species, or different annotation, whatever); in this case, they should definitively be encouraged to contributed PRs to the generation, and we should aim at hosting and supporting those officially from our framework: In this case, docs versioning, etc all all required
2) (my scenario) a reference or subreference that is used in the precise context of a lab project and has little utility outside that. Even versioning might be a confusing overlayer in this context. So maybe we could have a CustomAtlas class to which to pass the download url, and a cli tool for downloading those.

Still, it would be good if even case 2) ends up in the brainglobe folder, so that a suitable Atlas class can be instantiated passing the correct name (I would still like to refactor out all BGAtlas subclasses as mentioned in #44). However, it should be kept separated from all brainglobe parsing that relates to standard atlases. Maybe prepend something to the name, such as a `_` as in `_subregion_atlas_portugueslab_0.2um`?
Obviously this is just a convention we would encourage, people are free to name atlases in a way that don't make distinguishable from bg core ones and mess up stuff :p

**Comment by adamltyson** [comment]
Fully agree, all sounds good.

**Comment by FedeClaudi** [comment]
ja

**Comment by emilyjanedennis** [comment]
hey folks, I'd love to make my data brainrender/brainglobe friendly - any progress on this? I'm also happy to test out any guidelines you may be writing/work with you directly. Best, Emily (Brody lab)

**Comment by vigji** [comment]
Hi @emilyjanedennis! Very happy that you would be interested in this! Can you describe a bit your situation? What data you would need to distribute it? Is it for internal lab use, or for making it public? I am thinking about some restructuring to improve our atlas creation/versioning and deposit them with a DOI to happen in the next couple of months. Having some external usage case would be great if you are willing to work with us directly!

**Comment by emilyjanedennis** [comment]
We have an in-house rat atlas + annotated volume and want to make it publicly accessible along with a preprint of some neuronal tracing data, we aim to preprint/submit in the spring. At the minimum, knowing the exact needs for structuring the hierarchy (JSON file?) and other data formatting aspects to make it usable with brainrender/brainglobe would be super helpful. 

In my own lab starting in 2022 I'll also be working with atlas data and having a pipeline to make data broadly usable is something I'm really invested in so I'd be very happy to work directly with you all - feel free to follow up/connect by sending me an email at emilyjanedennis < a t > gmail.com

**Comment by adamltyson** [comment]
Closing - instructions to add a new atlas are [here](https://brainglobe.info/documentation/bg-atlasapi/adding-a-new-atlas.html)
