### ISSUE TITLE
bg-atlasapi doesn't work (at all) without a network connection.

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#57]
We check on GIN to see if there is a newer version of the atlas. We should keep a local copy of this file, and fall back onto it if we can't connect to the GIN server.

**Comment by vigji** [comment]
Very good and important point, I noticed this and I was trying to figure out to simulate offline in the tests

**Comment by adamltyson** [comment]
As a dumb workaround for a test, could you just have a "dummy" URL that doesn't respond?

**Comment by FedeClaudi** [comment]
yes we should defenetively fix this!

**Comment by vigji** [comment]
That would work, although it won't be a full test for normal atlas usage offline I think
