### ISSUE TITLE
Add a -h flag option for the CLI

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#81]
When you type an invalid command for the CLI, the help message isn't very helpful (it tells you to use another invalid command):
```
ValueError: Invalid command download. use "brainglobe -h for more info."
(atlas) atyson@enc2-node7:~/python/brainreg$ brainglobe -h                          
Usage: brainglobe [OPTIONS] COMMAND
Try 'brainglobe --help' for help.

Error: no such option: -h
```

Can we add a `-h` option with click (I've never used it)?

**Comment by FedeClaudi** [comment]
oh weird, I would've thought that `-h` would implemented automatically by click. It should be possible though.
