### ISSUE TITLE
Adding pycln

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#83]
Hi, 

Opening it here but valid throughout the org.
We could add [pycln](https://github.com/hadialqattan/pycln) to our pre-commit stack. 
It automatically removes unused imports from all files. I have set it up in `pyinspect`  to run before `flake8` so that it fixed is before `flake8` stops the commit from going through. 

Lemme know!

**Comment by FedeClaudi** [comment]
cc @adamltyson  @vigji

**Comment by vigji** [comment]
sounds good to me!

**Comment by adamltyson** [comment]
Yep sounds good.

**Comment by FedeClaudi** [comment]
Ooops, I got a 404 error when I first tried to open the issue, it seems that it opened it twice instread!
Sorry 'bout that
