### ISSUE TITLE
download progress bar to indicate when download will be completed

### ISSUE THREAD

**Issue by bendichter** [brainglobe/bg-atlasapi#85]
![image](https://user-images.githubusercontent.com/844306/95217851-a5ff8100-07c1-11eb-827c-dfbfac44f89d.png)

It would be nice if this display indicated the total size and/or the ETA of the download.

**Comment by bendichter** [comment]
same issue in command line version of progress bar

**Comment by FedeClaudi** [comment]
Thanks! 

It's a good idea, we will implement this. 

@adamltyson @vigji  I know we had decided not to use [rich](https://github.com/willmcgugan/rich) but it now works with Jupyter notebook so if that's okay for you I'd re-introduce it. 
I think that would mean that we can remove `tqdm` from the dependencies too.

**Comment by adamltyson** [comment]
@FedeClaudi yep sounds good. I don't use jupyter, so as long as @vigji is fine with it, it seems like a good idea.

**Comment by FedeClaudi** [comment]
me neither, but users will. I'll make it a point to double check that it works on both ;)

**Comment by vigji** [comment]
Good for me, if it now works on notebooks and adds this enhancement as well, yes! And removing a dependency is also a plus

**Comment by adamltyson** [comment]
Is this addressed now? Can we close?

**Comment by adamltyson** [comment]
Going to go with yes.
