### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#9]
Considering that this package (and others under the brainglobe umbrella) expose an API, we should think about documentation. 

I don't have much experience with this kind of documentation, but [building it with sphinx from the docstrings](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) seems like the easiest way. Does anyone have any other ideas or objections?

We should also decide on a standard format. `braintlas-api` looks to be using the numpy format currently. Ideally I'd like to move to the default sphinx/reST format, mostly because it's the format already used by brainrender, cellfinder, amap etc.

**Comment by vigji** [comment]
Youp! I was waiting for it (writing docs) a bit as I guess that in these first times of development and testing on our side things might change fast and in my experience it's quite easy to forget outdated docs around.

I personally don't like much the sphinx/reST format and would prefer either Numpy or Google format + napoleon sphinx tool. It should be possible to convert the docs format from one version to the other using [something like this](https://github.com/dadadel/pyment/) although I have not tried!
But I have no strong opinion there and would comply to the sphinx/reST format if you like it more

**Comment by adamltyson** [comment]
I was thinking that writing docs could be more useful for development (so that other developers can better understand what things do).

I also don't have a strong opinion about the docstring format. My main reason is that amap/cellfinder etc use reST, but as long as it's one of the ones that PyCharm can do automatically, I don't mind.

**Comment by FedeClaudi** [comment]
I don't mind either, as long as I don't have to manually change brainrender's format. I did that a while ago to start using reST and it's not fun :P

**Comment by FedeClaudi** [comment]
related to the ongoing discussion over here: https://github.com/brainglobe/brainatlas-api/pull/40#issuecomment-644635345

It would be good if the docs included a table with an overview of available atlases

**Comment by FedeClaudi** [comment]
> I don't have much experience with this kind of documentation, but building it with sphinx from the docstrings seems like the easiest way

@adamltyson  @vigji  is this what we're going for in the end?

**Comment by adamltyson** [comment]
I think so. I think I would favour API docs automatically generated from the docstrings, in addition to a small amount of manually edited markdown illustrating general concepts, and any user-facing command-line tools.

**Comment by vitay** [comment]
any news on that front? I am reviewing for JOSS and that is the only problem I see. At least the docstrings of the `BrainGlobeAtlas` class should be exposed in the documentation (although `help(BrainGlobeAtlas)` does the job).

On a more minor note, one item for the review is:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

It is quite implicit as the code is on github, but perhaps you can add a small paragraph to the README so I can check off the item.

**Comment by FedeClaudi** [comment]
Hi, 

I've added a short paragraph to the README (on the main branch) and to the [docs](https://docs.brainglobe.info/bg-atlasapi/contributing) with very simple guidelines for contributing. 

Regarding the docstrings, I have generate docs like [these for brainrender](https://docs.brainrender.info/autogenerated-docs/brainrender-autodocs/scene) and added them to the docs online: https://docs.brainglobe.info/autogenerate-docs/bg_atlas/core

Hope this is what you had in mind, but please do let use know if there is a better way to document this.

**Comment by vitay** [comment]
Great, thanks!

**Comment by vigji** [comment]
I guess we can close this. Long term there's some aesthetical improvements that can happen on the markdown generated docs but that is minor

**Comment by FedeClaudi** [comment]
Hey, do you want to open an issue in [pydoc2md](https://github.com/FedeClaudi/pydoc2md) with suggestions for improving things?
