### ISSUE TITLE
structure_from_coords finds too many regions

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#99]
![pp](https://user-images.githubusercontent.com/17436313/109146583-e99c5c80-775b-11eb-9530-d043ebdd456b.gif)

Hey guys, I'm making a probe planning app, as you can see above.
I use the `structure_from_coords` method to find through which brain regions the probe goes through. This works mostly fine but occasionally finds too much stuff:

For instance here:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/17436313/109146816-32541580-775c-11eb-9f2b-cf2a764d2040.png">

it finds some stuff in the hypothalamus, miles away from the probe. I think that this is a bug with the atlas function and not with my probe planner stuff, but might require some investigation.

**Comment by FedeClaudi** [comment]
I think I have figure it out. If the coordinates are outside of the atlas space, it returns a structure counting the distance from the opposide side (like if you were using negative indices to get an item in a list). 
There should be a check that if the coordinates are outside of where the brain outline is it should return None or raise an error

**Comment by vigji** [comment]
Thanks @FedeClaudi for the report?
Do you have a code snippet do to reproduce? If I just ask for coordinates outside the brain with an offset that matches the atlas shape I actually get an error with my code:

```
import numpy as np
from bg_atlasapi.bg_atlas import BrainGlobeAtlas

# This will automatically trigger the download of the zebrafish atlas. This atlas has a resolution of 1 um
atlas = BrainGlobeAtlas("mpin_zfish_1um")
atlas.structure_from_coords((500, 150, 300))  # return 833
atlas.structure_from_coords((500+974, 150, 300))  # gives an index error
```

**Comment by FedeClaudi** [comment]
Mmm that's weird, this example code:
```python

from brainrender import Scene
import numpy as np
s = Scene()

root = s.atlas.get_region('root')
p0 = root.centerOfMass()

x = np.linspace(p0[0], p0[0]+10000, 20)
for p in x:
    point = p0.copy()
    point[0] = p
    print(p, root.mesh.isInside(point), s.atlas.structure_from_coords(point, as_acronym=True, microns=True))

print(p0)

```

raises an Indexerror, but pretty much the same code in my app didn't, it gave bogus results instead. Weird...

**Comment by vigji** [comment]
Is is possible that within the program there are some try-except that leave some default values unaltered?

**Comment by FedeClaudi** [comment]
I think you are right, sorry it seems that it's not a bg-atlasapi issue after all. Thanks Luigi
